const FIELD_IDS = {
  job: {
    companyName: ['job_company_name_block', 'job_company_name_input'],
    roleTitle: ['job_role_title_block', 'job_role_title_input'],
    locationSummary: ['job_location_summary_block', 'job_location_summary_input'],
    workArrangements: ['job_work_arrangements_block', 'job_work_arrangements_checkbox'],
    employmentTypes: ['job_employment_types_block', 'job_employment_types_checkbox'],
    compensationValue: ['job_compensation_value_block', 'job_compensation_value_input'],
    compensationComponents: ['job_compensation_components_block', 'job_compensation_components_checkbox'],
    visaPolicy: ['job_visa_policy_block', 'job_visa_policy_radio'],
    relationship: ['job_relationship_block', 'job_relationship_radio'],
    links: ['job_links_block', 'job_links_input'],
    skills: ['job_skills_block', 'job_skills_input'],
    summary: ['job_summary_block', 'job_summary_input'],
    allowThreadQuestions: ['job_thread_questions_block', 'job_thread_questions_checkbox'],
  },
  candidate: {
    headline: ['candidate_headline_block', 'candidate_headline_input'],
    locationSummary: ['candidate_location_summary_block', 'candidate_location_summary_input'],
    workArrangements: ['candidate_work_arrangements_block', 'candidate_work_arrangements_checkbox'],
    availabilityModes: ['candidate_availability_modes_block', 'candidate_availability_modes_checkbox'],
    engagementTypes: ['candidate_engagement_types_block', 'candidate_engagement_types_checkbox'],
    compensationDisclosure: ['candidate_compensation_disclosure_block', 'candidate_compensation_disclosure_radio'],
    compensationValue: ['candidate_compensation_value_block', 'candidate_compensation_value_input'],
    compensationComponents: ['candidate_compensation_components_block', 'candidate_compensation_components_checkbox'],
    visaPolicy: ['candidate_visa_policy_block', 'candidate_visa_policy_radio'],
    relationship: ['candidate_relationship_block', 'candidate_relationship_radio'],
    links: ['candidate_links_block', 'candidate_links_input'],
    skills: ['candidate_skills_block', 'candidate_skills_input'],
    notes: ['candidate_notes_block', 'candidate_notes_input'],
    allowThreadQuestions: ['candidate_thread_questions_block', 'candidate_thread_questions_checkbox'],
  },
};

module.exports = { FIELD_IDS };
